### PR TITLE
Relax dependency versions for Ruby 2.4

### PR DESCRIPTION
**Pull request by obahareth**

### CODE REVIEW

**Comment by abrom** [comment]
@obahareth  are you able to add `2.4.0` to the travis.yml?

**Comment by obahareth** [comment]
I'll add it either today or tomorrow.

**Comment by abrom** [comment]
Nice one, thanks @obahareth ! 

Regarding the last travis build, I suspect there might be a load time issue with the static `sleep 2` not quite being enough (if the server is resource constrained in some way). I kicked the builds and they went green. Given Tika is apparently going to remove the server options some time soon I'm thinking probably safe to let it slide. Of course not related to your change anyway!

**Comment by obahareth** [comment]
Yeah I was a bit worried there, I also had to manually require `time` from stdlib because `Time.parse` wasn't being found. I'm not sure why that happened exactly, maybe one of the gems I allowed to use newer versions was requiring `time` for us.

**Comment by abrom** [comment]
Ok, pushed to rubygems as `1.14.3`

**Pull request merged**
